src/main/java/ua/omld/ibanking/domain/Client.java
/*
 * Client.java
 * Copyright (c) 2018 Oleksii Kostetskyi.
 *
 * This software is licensed under GPL v2
 */

package ua.omld.ibanking.domain;

import ua.omld.ibanking.utils.validators.Patterns;
import ua.omld.ibanking.utils.validators.StringValidator;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents client of the bank
 */
public class Client implements Entity<Long> {

    private Long id;
    private String surname;
    private String name;
    private String patronymic;
    private LocalDate birthDate;
    private String taxNumber;
    private List<BankAccount> bankAccounts;

    private Client() {
        bankAccounts = new ArrayList<>();
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getSurname() {
        return surname;
    }

    public String getName() {
        return name;
    }

    public String getPatronymic() {
        return patronymic;
    }

    public String fullName() {
        return surname + " " + name + " " + patronymic;
    }

    public String shortFullName() {
        return surname + " " + name.charAt(0) + ". " + patronymic.charAt(0) + ".";
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }

    public String getTaxNumber() {
        return taxNumber;
    }

    public List<BankAccount> getBankAccounts() {
        return bankAccounts;
    }

    public void setBankAccounts(List<BankAccount> bankAccounts) {
        this.bankAccounts = bankAccounts;
    }

    public void addBankAccount(BankAccount bankAccount) {
        this.bankAccounts.add(bankAccount);
    }

    public void removeBankAccount(BankAccount bankAccount) {
        this.bankAccounts.remove(bankAccount);
    }

    @Override
    public boolean equals(Object o) {

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Client client = (Client) o;
        return Objects.equals(id, client.id) &&
                Objects.equals(surname, client.surname) &&
                Objects.equals(name, client.name) &&
                Objects.equals(patronymic, client.patronymic) &&
                Objects.equals(birthDate, client.birthDate) &&
                Objects.equals(taxNumber, client.taxNumber);
    }

    @Override
    public int hashCode() {
        return this.getClass().hashCode()
                + Objects.hashCode(id)
                + 3 * Objects.hashCode(surname)
                + 5 * Objects.hashCode(name)
                + 7 * Objects.hashCode(patronymic)
                + 9 * Objects.hashCode(birthDate)
                + 11 * Objects.hashCode(taxNumber);
    }

    @Override
    public String toString() {
        return "Client{" +
                "id=" + id +
                ", surname='" + surname + '\'' +
                ", name='" + name + '\'' +
                ", patronymic='" + patronymic + '\'' +
                ", birthDate=" + birthDate +
                ", taxNumber='" + taxNumber + '\'' +
                '}';
    }

    public static ClientBuilder getBuilder(){
        return new ClientBuilder();
    }

    /**
     * Builds Client object
     */
    public static final class ClientBuilder {
        private Long id;
        private String surname;
        private String name;
        private String patronymic;
        private LocalDate birthDate;
        private String taxNumber;
        private List<BankAccount> bankAccounts;


        private ClientBuilder() {
        }

        public ClientBuilder setId(Long id) {
            this.id = id;
            return this;
        }

        public ClientBuilder setSurname(String surname) {
            this.surname = surname;
            return this;
        }

        public ClientBuilder setName(String name) {
            this.name = name;
            return this;
        }

        public ClientBuilder setPatronymic(String patronymic) {
            this.patronymic = patronymic;
            return this;
        }

        public ClientBuilder setBirthDate(LocalDate birthDate) {
            this.birthDate = birthDate;
            return this;
        }

        public ClientBuilder setTaxNumber(String taxNumber) {
            StringValidator taxNumberValidator = new StringValidator(Patterns.PERSON_TAX_NUMBER);
            if (taxNumberValidator.validate(taxNumber)) {
                this.taxNumber = taxNumber;
            }
            return this;
        }

        public ClientBuilder setBankAccounts(List<BankAccount> bankAccounts) {
            this.bankAccounts = bankAccounts;
            return this;
        }

        public Client build() {
            Client client = new Client();
            client.id = id;
            client.surname = surname;
            client.name = name;
            client.patronymic = patronymic;
            client.birthDate = birthDate;
            client.taxNumber = taxNumber;
            client.bankAccounts = new ArrayList<>();
            if (bankAccounts != null)
                client.bankAccounts.addAll(bankAccounts);
            return client;
        }
    }
}

src/main/java/ua/omld/ibanking/domain/Transaction.java
/*
 * Transaction.java
 * Copyright (c) 2018 Oleksii Kostetskyi.
 *
 * This software is licensed under GPL v2
 */

package ua.omld.ibanking.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represent bank transactions:
 * - transfer;
 * - payment;
 */
public class Transaction implements Entity<Long> {

    private Long id;
    private LocalDateTime creationDateTime;
    private LocalDateTime executionDateTime;
    private BigDecimal amount;
    private BigDecimal fee;
    private TransactionStatus status;
    private TransactionType type;
    private TransactionPerson sender;
    private TransactionPerson beneficiary;
    private String description;

    public Transaction() {
        this.sender = new TransactionPerson();
        this.beneficiary = new TransactionPerson();
    }

    protected Transaction(Transaction that) {
        this();
        this.id = that.id;
        this.creationDateTime = that.creationDateTime;
        this.executionDateTime = that.executionDateTime;
        this.amount = that.amount;
        this.fee = that.fee;
        this.status = that.status;
        this.type = that.type;
        this.sender = that.sender;
        this.beneficiary = that.beneficiary;
        this.description = that.description;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreationDateTime() {
        return creationDateTime;
    }

    public void setCreationDateTime(LocalDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
    }

    public LocalDateTime getExecutionDateTime() {
        return executionDateTime;
    }

    public void setExecutionDateTime(LocalDateTime executionDateTime) {
        this.executionDateTime = executionDateTime;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getFee() {
        return fee;
    }

    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    public TransactionStatus getStatus() {
        return status;
    }

    public void setStatus(TransactionStatus status) {
        this.status = status;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }

    public void setSenderName(String name) {
        this.sender.name = name;
    }

    public String getSenderName() {
        return this.sender.name;
    }

    public void setSenderCode(String code) {
        this.sender.personCode = code;
    }

    public String getSenderCode() {
        return this.sender.personCode;
    }

    public void setSenderBankCode(String bankCode) {
        this.sender.bankCode = bankCode;
    }

    public String getSenderBankCode() {
        return this.sender.bankCode;
    }

    public void setSenderBankAccount(String bankAccountNumber) {
        this.sender.bankAccountNumber = bankAccountNumber;
    }

    public String getSenderBankAccountNumber() {
        return this.sender.bankAccountNumber;
    }

    public void setBeneficiaryName(String name) {
        this.beneficiary.name = name;
    }

    public String getBeneficiaryName() {
        return this.beneficiary.name;
    }

    public void setBeneficiaryCode(String code) {
        this.beneficiary.personCode = code;
    }

    public String getBeneficiaryCode() {
        return this.beneficiary.personCode;
    }

    public void setBeneficiaryBankCode(String bankCode) {
        this.beneficiary.bankCode = bankCode;
    }

    public String getBeneficiaryBankCode() {
        return this.beneficiary.bankCode;
    }

    public void setBeneficiaryBankAccount(String bankAccountNumber) {
        this.beneficiary.bankAccountNumber = bankAccountNumber;
    }

    public String getBeneficiaryBankAccountNumber() {
        return this.beneficiary.bankAccountNumber;
    }

    public TransactionPerson getSender() {
        return sender;
    }

    public void setSender(TransactionPerson sender) {
        this.sender = sender;
    }

    public TransactionPerson getBeneficiary() {
        return beneficiary;
    }

    public void setBeneficiary(TransactionPerson beneficiary) {
        this.beneficiary = beneficiary;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Transaction that = (Transaction) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(creationDateTime, that.creationDateTime) &&
                Objects.equals(executionDateTime, that.executionDateTime) &&
                Objects.equals(amount, that.amount) &&
                Objects.equals(fee, that.fee) &&
                status == that.status &&
                type == that.type &&
                Objects.equals(sender, that.sender) &&
                Objects.equals(beneficiary, that.beneficiary) &&
                Objects.equals(description, that.description);
    }

    @Override
    public int hashCode() {
        return this.getClass().hashCode()
                + Objects.hashCode(id)
                + 3 * Objects.hashCode(creationDateTime)
                + 5 * Objects.hashCode(executionDateTime)
                + 7 * Objects.hashCode(amount)
                + 9 * Objects.hashCode(fee)
                + 11 * Objects.hashCode(status)
                + 13 * Objects.hashCode(type)
                + 15 * Objects.hashCode(sender)
                + 17 * Objects.hashCode(beneficiary)
                + 19 * Objects.hashCode(description);
    }

    public static TransactionBuilder getBuilder(){
        return new TransactionBuilder();
    }

    /**
     * Builds Transaction object
     */
    public static final class TransactionBuilder {
        private Long id;
        private LocalDateTime creationDateTime;
        private LocalDateTime executionDateTime;
        private BigDecimal amount;
        private BigDecimal fee;
        private TransactionStatus status;
        private TransactionType type;
        private TransactionPerson sender;
        private TransactionPerson beneficiary;
        private String description;

        private TransactionBuilder() {
            sender = new TransactionPerson();
            beneficiary = new TransactionPerson();
        }

        public TransactionBuilder setId(Long id) {
            this.id = id;
            return this;
        }

        public TransactionBuilder setCreationDateTime(LocalDateTime creationDateTime) {
            this.creationDateTime = creationDateTime;
            return this;
        }

        public TransactionBuilder setExecutionDateTime(LocalDateTime executionDateTime) {
            this.executionDateTime = executionDateTime;
            return this;
        }

        public TransactionBuilder setAmount(BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        public TransactionBuilder setFee(BigDecimal fee) {
            this.fee = fee;
            return this;
        }

        public TransactionBuilder setStatus(TransactionStatus status) {
            this.status = status;
            return this;
        }

        public TransactionBuilder setType(TransactionType type) {
            this.type = type;
            return this;
        }

        public TransactionBuilder setSender(TransactionPerson sender) {
            this.sender = sender;
            return this;
        }

        public TransactionBuilder setBeneficiary(TransactionPerson beneficiary) {
            this.beneficiary = beneficiary;
            return this;
        }

        public TransactionBuilder setSenderName(String name) {
            this.sender.name = name;
            return this;
        }

        public TransactionBuilder setSenderCode(String code) {
            this.sender.personCode = code;
            return this;
        }

        public TransactionBuilder setSenderBankCode(String bankCode) {
            this.sender.bankCode = bankCode;
            return this;
        }

        public TransactionBuilder setSenderBankAccount(String bankAccountNumber) {
            this.sender.bankAccountNumber = bankAccountNumber;
            return this;
        }

        public TransactionBuilder setBeneficiaryName(String name) {
            this.beneficiary.name = name;
            return this;
        }

        public TransactionBuilder setBeneficiaryCode(String code) {
            this.beneficiary.personCode = code;
            return this;
        }

        public TransactionBuilder setBeneficiaryBankCode(String bankCode) {
            this.beneficiary.bankCode = bankCode;
            return this;
        }

        public TransactionBuilder setBeneficiaryBankAccount(String bankAccountNumber) {
            this.beneficiary.bankAccountNumber = bankAccountNumber;
            return this;
        }

        public TransactionBuilder setDescription(String description) {
            this.description = description;
            return this;
        }

        public Transaction build() {
            Transaction transaction = new Transaction();
            transaction.id = id;
            transaction.creationDateTime = creationDateTime;
            transaction.executionDateTime = executionDateTime;
            transaction.amount = amount;
            transaction.fee = fee;
            transaction.status = status;
            transaction.type = type;
            transaction.sender = sender;
            transaction.beneficiary = beneficiary;
            transaction.description = description;
            return transaction;

src/main/java/ua/omld/ibanking/domain/TransactionStatus.java
/*
 * TransactionStatus.java
 * Copyright (c) 2018 Oleksii Kostetskyi.
 *
 * This software is licensed under GPL v2
 */

package ua.omld.ibanking.domain;

/**
 * Represent status of bank transaction during processing.
 */
public enum TransactionStatus {

    CREATED("transaction.status.created"),
    ONCHECK("transaction.status.oncheck"),
    COMPLETED("transaction.status.completed"),
    DECLINED("transaction.status.declined");

    private String status;

    TransactionStatus(String status) {
        this.status = status;
    }

    public String getStatusString() {
        return status;
    }

}

src/main/webapp/WEB-INF/jsp/client/accounts.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="pages.client.accounts.title" scope="request"/>
<jsp:include page="/WEB-INF/jsp/includes/html_header.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_messages.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_errors.jsp"/>
<c:if test="${not empty accounts}">
    <p><fmt:message bundle="${views}" key="pages.client.accounts.accountsList"/></p>
    <br>
    <table id="accounts">
        <tr>
            <th class="theader"><fmt:message bundle="${views}" key="accounts.number"/></th>
            <th class="theader"><fmt:message bundle="${views}" key="accounts.balance"/></th>
            <th class="theader"><fmt:message bundle="${views}" key="accounts.type"/></th>
        </tr>
    <c:forEach var="account" items="${accounts}">
        <tr>
            <td class="string"><a href="?id=${account.id}">${account.number}</a></td>
            <td class="number">${account.balance}</td>
            <c:if test="${account['class'].simpleName == 'DepositAccount'}">
                <td class="string"><fmt:message bundle="${views}" key="accounts.depositAccount"/></td>
            </c:if>
            <c:if test="${account['class'].simpleName == 'CreditAccount'}">
                <td class="string"><fmt:message bundle="${views}" key="accounts.creditAccount"/></td>
            </c:if>
        </tr>
    </c:forEach>
    </table>
    <br>
</c:if>
<jsp:include page="/WEB-INF/jsp/includes/html_footer.jsp" />

src/main/webapp/WEB-INF/jsp/client/payments.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="pages.client.payments.title" scope="request"/>
<jsp:include page="/WEB-INF/jsp/includes/html_header.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_messages.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_errors.jsp"/>
<c:if test="${empty payComplete}">
    <c:if test="${not empty accounts}">
    <form id="payment" class="flex-column" action = "./payments" method="POST">
        <p><fmt:message bundle="${views}" key="pages.client.payments.byDetails"/></p>
        <c:if test="${not empty invoice}">
            <c:set var="benefName" value="${invoice.beneficiaryName}" />
            <c:set var="benefCode" value="${invoice.beneficiaryCode}" />
            <c:set var="benefBank" value="${invoice.bankCode}" />
            <c:set var="benefAcc" value="${invoice.bankAccount}" />
            <c:set var="reference" value="${invoice.description}" />
            <c:set var="amount" value="${invoice.amount}" />
            <c:set var="fee" value="${fee}" />
        </c:if>
        <fieldset>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="pages.client.payments.selectAccount"/></label>
                </div>
                <select class="accounts" name="account" id="account_id" required <c:if test="${not empty fee}">disabled</c:if>>
                <c:choose>
                    <c:when test="${empty fee}">
                        <c:forEach var="account" items="${accounts}">
                            <c:if test="${account['class'].simpleName == 'DepositAccount'}">
                                <fmt:message bundle="${views}" key="accounts.depositAccount" var="accType"/>
                            </c:if>
                            <c:if test="${account['class'].simpleName == 'CreditAccount'}">
                                <fmt:message bundle="${views}" key="accounts.creditAccount" var="accType"/>
                            </c:if>
                            <option value="${account.id}">${account.number} (${accType}): ${account.balance}</option>
                        </c:forEach>
                    </c:when>
                    <c:otherwise>
                        <c:if test="${account['class'].simpleName == 'DepositAccount'}">
                            <fmt:message bundle="${views}" key="accounts.depositAccount" var="accType"/>
                        </c:if>
                        <c:if test="${account['class'].simpleName == 'CreditAccount'}">
                            <fmt:message bundle="${views}" key="accounts.creditAccount" var="accType"/>
                        </c:if>
                        <option value="${account.id}">${account.number} (${accType}): ${account.balance}</option>
                    </c:otherwise>
                </c:choose>
                </select>
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.beneficiary.name"/></label>
                </div>
                <input type="text" id="beneficiary_name" name="beneficiary_name" value="<c:out value="${benefName}"/>" required <c:if test="${not empty fee}">disabled</c:if> >
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.beneficiary.code"/></label>
                </div>
                <input type="text" id="beneficiary_code" name="beneficiary_code" pattern='[0-9]{8,10}' value="${benefCode}" required <c:if test="${not empty fee}">disabled</c:if> >
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.beneficiary.bankCode"/></label>
                </div>
                <input type="text" id="beneficiary_bank" name="beneficiary_bank" pattern='[0-9]{6}' value="${benefBank}" required <c:if test="${not empty fee}">disabled</c:if> >
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.beneficiary.account"/></label>
                </div>
                <input type="text" id="beneficiary_account" name="beneficiary_account" pattern='[0-9]{10,19}' value="${benefAcc}" required <c:if test="${not empty fee}">disabled</c:if> >
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.reference"/></label>
                </div>
                <textarea id="description" name="description" required <c:if test="${not empty fee}">disabled</c:if> >${reference}</textarea>
            </div>
            <div class="form-row">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.amount"/></label>
                </div>
                <input type="text" id="amount" name="amount" placeholder="0.00" pattern="^\d+(?:\.\d{1,2})?$" value="${amount}" required <c:if test="${not empty fee}">disabled</c:if> >
            </div>
        </fieldset>
        <c:if test="${not empty fee}">
            <div class="form-row fee">
                <div class="label">
                    <label><fmt:message bundle="${views}" key="payment.fee"/></label>
                </div>
                <input type="text" id="fee" name="fee" placeholder="0.00" pattern="^\d+(?:\.\d{1,2})?$" value="${fee}" disabled>
            </div>
        </c:if>
        <div class="action">
            <c:choose>
                <c:when test="${empty fee}" >
                    <input type="hidden" name="suffix" value="verify">
                    <input type="submit" value="<fmt:message bundle="${views}" key="pages.client.payments.button.continue"/>">
                </c:when>
                <c:otherwise>
                    <input type="hidden" name="suffix" value="pay">
                    <input type="submit" value="<fmt:message bundle="${views}" key="pages.client.payments.button.pay"/>">
                </c:otherwise>
            </c:choose>
        </div>
    </form>
    </c:if>
</c:if>
<jsp:include page="/WEB-INF/jsp/includes/html_footer.jsp" />

src/main/webapp/WEB-INF/jsp/client/requests.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="pages.client.requests.title" scope="request"/>
<jsp:include page="/WEB-INF/jsp/includes/html_header.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_messages.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_errors.jsp"/>
<c:choose>
    <c:when test="${(not empty creditPresent) && (creditPresent == true)}">
        <p><fmt:message bundle="${views}" key="pages.client.requests.creditPresent"/></p>
    </c:when>
    <c:otherwise>
        <p><fmt:message bundle="${views}" key="pages.client.requests.requestForm"/></p>
        <form id="payment" class="flex-column" action = "./requests" method="POST">
            <fieldset>
                <div class="form-row">
                    <div class="label">
                        <label><fmt:message bundle="${views}" key="request.amount"/></label>
                    </div>
                    <input type="text" id="amount" name="amount" required >
                </div>
                <div class="form-row">
                    <div class="label">
                        <label><fmt:message bundle="${views}" key="request.term"/></label>
                    </div>
                    <input type="number" id="term" name="term" min="0" step="1" value="24" required >
                </div>
            </fieldset>
            <div class="action">
                <input type="submit" value="<fmt:message bundle="${views}" key="pages.client.requests.button.submit"/>">
            </div>
        </form>
    </c:otherwise>
</c:choose>
<hr>
<c:choose>
    <c:when test="${empty requests}">
        <p><fmt:message bundle="${views}" key="pages.client.requests.noRequests"/></p>
    </c:when>
    <c:otherwise>
        <p><fmt:message bundle="${views}" key="pages.client.requests.requestsList"/></p>
        <br>
        <table id="requests">
            <tr>
                <th class="theader"><fmt:message bundle="${views}" key="request.creationDateTime"/></th>
                <th class="theader"><fmt:message bundle="${views}" key="request.status"/></th>
                <th class="theader"><fmt:message bundle="${views}" key="request.amount"/></th>
                <th class="theader"><fmt:message bundle="${views}" key="request.term"/></th>
                <th class="theader"><fmt:message bundle="${views}" key="request.approvedAmount"/></th>
                <th class="theader"><fmt:message bundle="${views}" key="request.approvedValidity"/></th>
            </tr>
            <c:forEach var="request" items="${requests}">
                <tr>
                    <fmt:parseDate value="${request.creationDateTime}" pattern="yyyy-MM-dd'T'HH:mm:ss" var="creationDateTime" type="both" />
                    <td class="date"><fmt:formatDate value="${creationDateTime}" type="both"  dateStyle="medium"/></td>
                    <td class="string"><fmt:message bundle="${views}" key="${request.status.statusString}"/></td>
                    <td class="number">${request.amount}</td>
                    <td class="string">${request.term.months}</td>
                    <td class="number">${request.approvedAmount}</td>
                    <fmt:parseDate value="${request.approvedValidity}" pattern="yyyy-MM-dd" var="approvedValidity" />
                    <td class="date"><fmt:formatDate value="${approvedValidity}" type="date"  dateStyle="medium"/></td>
                </tr>
            </c:forEach>
        </table>
        <br>
    </c:otherwise>
</c:choose>
<jsp:include page="/WEB-INF/jsp/includes/html_footer.jsp" />

src/main/webapp/WEB-INF/jsp/client/transaction_info.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="pages.client.transaction.title" scope="request"/>
<jsp:include page="/WEB-INF/jsp/includes/html_header.jsp"/>
<jsp:include page="/WEB-INF/jsp/includes/_errors.jsp"/>
<p><a href="./accounts?id=${param.account}"><fmt:message bundle="${views}" key="pages.client.transaction.return"/></a></p>
<br>
<p><fmt:message bundle="${views}" key="pages.client.transaction.title"/></p>
<br>
<table id="transaction_info">
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.number"/></td>
        <td class="number">${transaction.id}</td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.creationTime"/></td>
        <fmt:parseDate value="${transaction.creationDateTime}" pattern="yyyy-MM-dd'T'HH:mm:ss" var="creationDateTime" type="both" />
        <td class="date"><fmt:formatDate value="${creationDateTime}" type="both"  dateStyle="short"/></td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.executionTime"/></td>
        <fmt:parseDate value="${transaction.executionDateTime}" pattern="yyyy-MM-dd'T'HH:mm:ss" var="executionDateTime" type="both" />
        <td class="date"><fmt:formatDate value="${executionDateTime}" type="both"  dateStyle="short"/></td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.sender"/></td>
        <td class="string">${transaction.senderName}</td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.beneficery"/></td>
        <td class="string">${transaction.beneficiaryName}</td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.status"/></td>
        <td class="string"><fmt:message bundle="${views}" key="${transaction.status.statusString}"/></td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.amount"/></td>
        <td class="number">${transaction.amount}</td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.fee"/></td>
        <td class="number">${transaction.fee}</td>
    </tr>
    <tr>
        <td class="string"><fmt:message bundle="${views}" key="transaction.description"/></td>
        <td class="string">${transaction.description}</td>
    </tr>
</table>
<br>
<jsp:include page="/WEB-INF/jsp/includes/html_footer.jsp" />

src/main/webapp/WEB-INF/jsp/client/transactions_block.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<table id="transactions">
    <tr>
        <th class="theader"><fmt:message bundle="${views}" key="transaction.number"/></th>
        <th class="theader"><fmt:message bundle="${views}" key="pages.client.transaction.date"/></th>
        <th class="theader"><fmt:message bundle="${views}" key="transaction.beneficery"/></th>
        <th class="theader"><fmt:message bundle="${views}" key="transaction.status"/></th>
        <th class="theader"><fmt:message bundle="${views}" key="transaction.amount"/></th>
    </tr>
<c:forEach var="transaction" items="${account.transactions}">
    <tr>
        <td class="number"><a href="./transaction?id=${transaction.id}&account=${account.id}">${transaction.id}</a></td>
        <fmt:parseDate value="${transaction.creationDateTime}" pattern="yyyy-MM-dd'T'HH:mm:ss" var="creationDateTime" type="both" />
        <td class="date"><fmt:formatDate value="${creationDateTime}" type="both"  dateStyle="short"/></td>
        <td class="string">${transaction.beneficiaryName}</td>
        <td class="string">
            <fmt:message bundle="${views}" key="${transaction.status.statusString}"/>
        </td>
        <td class="number">${transaction.amount}</td>
    </tr>
</c:forEach>
</table>